author: Qassandra Chaidir
name: Simple Split
description: This action will split comment body by separator
branding:
  icon: feather
  color: white
inputs:
  comment:
    description: Comment to split
    required: true
outputs:
  result:
    description: Action Result
runs:
  using: node12
  main: ./dist/index.js
