author: Qassandra Chaidir
name: Simple Split
description: This action will split comment body by separator
branding:
  icon: feather
  color: white
inputs:
  comment:
    description: Comment to split
    required: true
  limit:
    description: Limit on the number of substrings to be included in the array
    default: '-1'
    required: false
outputs:
  result:
    description: Action Result
runs:
  using: node12
  main: ./dist/index.js
